- name: Webserver setup
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install apache2
      ansible.builtin.apt: 
        name: apache2
        state: present

    - name: Start apache2 service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
